### ISSUE TITLE
model.py中计算pred_rating的疑问

### ISSUE THREAD

**Issue by cscy117** [mtics/FedRAP#4]
作者您好，在您的论文里面，pred_rating的计算是user_embedding与(item_local_embedding+item_global_embedding)做内积，如下图所示：
![image](https://github.com/user-attachments/assets/5f3dfb86-fda7-4877-a14a-466176abd2ac)
但是在model.py中好像并没有看到user_embedding参与运算
![image](https://github.com/user-attachments/assets/36fd2cb8-57e9-46a1-97d2-aed3662cf30f)
请问这是为什么呢

**Comment by mtics** [comment]
您好，u_i作为affine_output的参数，无需显式定义。

**Comment by cscy117** [comment]
感谢您的回复以及对开源的贡献！
